### ISSUE TITLE
cannot download the efficientnet-b0-355c32eb.pth,is the addr right?

### ISSUE THREAD

**Issue by mathpopo** [toandaominh1997/EfficientDet.Pytorch#135]
Downloading: "http://storage.googleapis.com/public-models/efficientnet/efficientnet-b0-355c32eb.pth" to /home/.cache/torch/checkpoints/efficientnet-b0-355c32eb.pth
Traceback (most recent call last):
 
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden

**Comment by SuJiaKuan** [comment]
It seems that the pre-trained model is not available currently. My solution is to download `efficientnet-b0-355c32eb.pth` from [here](https://github.com/lukemelas/EfficientNet-PyTorch/releases/tag/1.0) and save it at `~/cache/torch/checkpoints`

**Comment by mathpopo** [comment]
@SuJiaKuan  oh ,thanks!it help me .
