### ISSUE TITLE
[CUDA/CPU ERROR] when I trained on my data, I found this error:

### ISSUE THREAD

**Issue by Observerspy** [toandaominh1997/EfficientDet.Pytorch#2]
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weiqiang/cancer/code/models/efficientdet.py", line 130, in forward
    P1, P2, P3, P4, P5, P6, P7 = self.efficientnet(inputs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 204, in forward
    P1, P2, P3, P4, P5, P6, P7 = self.extract_features(inputs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 190, in extract_features
    x = MBConvBlock(block_args, self._global_params)(x, drop_connect_rate = drop_connect_rate)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 78, in forward
    x = self._swish(self._bn1(self._depthwise_conv(x)))
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/utils.py", line 144, in forward
    x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
**RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'weight'**

**Comment by dhananjaisharma10** [comment]
> RuntimeError: Caught RuntimeError in replica 0 on device 0.
> Original Traceback (most recent call last):
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
> output = module(*input, **kwargs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/weiqiang/cancer/code/models/efficientdet.py", line 130, in forward
> P1, P2, P3, P4, P5, P6, P7 = self.efficientnet(inputs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 204, in forward
> P1, P2, P3, P4, P5, P6, P7 = self.extract_features(inputs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 190, in extract_features
> x = MBConvBlock(block_args, self._global_params)(x, drop_connect_rate = drop_connect_rate)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/model.py", line 78, in forward
> x = self._swish(self._bn1(self._depthwise_conv(x)))
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 547, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/weiqiang/anaconda3/lib/python3.7/site-packages/efficientnet_pytorch/utils.py", line 144, in forward
> x = F.conv2d(x, self.weight, self.bias, self.stride, self.padding, self.dilation, self.groups)
> **RuntimeError: Expected object of backend CUDA but got backend CPU for argument #2 'weight'**

Hi! How did you solve this error? I realize that it's because of the **new** MBConvBlock's being used in the extract features function. In my opinion, it's bad coding as the originally declared self._blocks Module list is not even being used.

**Comment by Observerspy** [comment]
@dhananjaisharma10 Infact, I just add
`if torch.cuda.is_available():
    torch.set_default_tensor_type('torch.cuda.FloatTensor')`
in my own train.py.
