### ISSUE TITLE
Need (images, annotations) but dataset.__getitem__() return {'image': img, 'bboxes': bbox, 'category_id': labels}  

### ISSUE THREAD

**Issue by AlexLuya** [toandaominh1997/EfficientDet.Pytorch#23]
will this work?

**Comment by toandaominh1997** [comment]
@AlexLuya  Your question is not clear, yes, voc or coco has images and anotations. And I have read it to return {'image': img, 'bboxes': bbox, 'category_id': labels}

**Comment by AlexLuya** [comment]
@toandaominh1997 sorry,haven't noticed  collate_fn provided@toandaominh1997 sorry,haven't noticed  collate_fn provided
