### ISSUE TITLE
Readme training part error

### ISSUE THREAD

**Issue by bruzat** [toandaominh1997/EfficientDet.Pytorch#34]
Hi,
You need to update https://github.com/toandaominh1997/EfficientDet.Pytorch#training-efficientdet 

**Change :** 

- To train EfficientDet using the train script simply specify the parameters listed in train.py as a flag or manually change them.

`python train.py --model_name effcientdet-d0 # Example`

- With VOC Dataset:

`python train.py --dataset_root /root/data/VOCdevkit/ --n effcientdet-d0 # Example`

**to** :

- To train EfficientDet using the train script simply specify the parameters listed in train.py as a flag or manually change them.

`python train.py --model_name efficientdet-d0 # Example`

- With VOC Dataset:

`python train.py --dataset_root /root/data/VOCdevkit/ --network efficientdet-d0 # Example`

Thank you for this good repository

**Comment by toandaominh1997** [comment]
@bruzat Thank for your changes. I fixed it. Thank so much
