### ISSUE TITLE
train error

### ISSUE THREAD

**Issue by NoahBU** [toandaominh1997/EfficientDet.Pytorch#45]
OS:ubuntu18.04
RTX 1080ti * 1

I train efficientdet-b0 using:
python3 train.py --dataset VOC --dataset_root /home/**/data/VOCdevkit/ --network effcientdet-d0 --batch_size 8
Erro shows:
Traceback (most recent call last):
  File "train.py", line 93, in <module>
    transform=get_augumentation(phase='train', width=EFFICIENTDET[args.network]['input_size'], height=EFFICIENTDET[args.network]['input_size']))
KeyError: 'effcientdet-d0'

could you tell me how to fix this error ?

**Comment by toandaominh1997** [comment]
@NoahBU It looks like you are on the wrong syntax. Please replace --network effcientdet-d0 to --network efficientdet-d0. Thanks

**Comment by NoahBU** [comment]
> @NoahBU It looks like you are on the wrong syntax. Please replace --network effcientdet-d0 to --network efficientdet-d0. Thanks

issue solved!  thanks!

**Comment by ma3252788** [comment]
Hello, I changed to efficiencydet-d0, but it still does n’t work
![](https://ypyssl.machunjie.com/machunjie/20200109233959.png)

![](https://ypyssl.machunjie.com/machunjie/20200109234030.png)

Thank you !

**Comment by inFreedom92** [comment]
@ma3252788 
it's "efficientdet-d0" not "efficiencydet-d0"

**Comment by milleniums** [comment]
> Hello, I changed to efficiencydet-d0, but it still does n’t work

Hello, I changed to efficiencydet-d0, but it still does n’t work

**Comment by sihatafnan** [comment]
@ma3252788 , I am facing the same problem.Did you solve it?

**Comment by ma3252788** [comment]
> @ma3252788 , I am facing the same problem.Did you solve it?

I'm sorry, I didn't solve it, so I gave up this

**Comment by sihatafnan** [comment]
It was just a spelling mistake😅😪
