### ISSUE TITLE
KeyError: 'efficiencydet-d0'

### ISSUE THREAD

**Issue by ma3252788** [toandaominh1997/EfficientDet.Pytorch#81]
Hello, I changed to efficiencydet-d0, but it still does n’t work
![](https://ypyssl.machunjie.com/machunjie/20200109233959.png)

![](https://ypyssl.machunjie.com/machunjie/20200109234030.png)

Thank you !

**Comment by ma3252788** [comment]
#45 I followed this question but still not working

**Comment by ma3252788** [comment]
I just use :python train.py --dataset VOC --dataset_root /home/ubuntu/bigdisk/DataSets/VOC/VOCdevkit/ --network efficientdet-d0 --batch_size=14

And it works well

**Comment by chen1234520** [comment]
i get the  same error, Have you solved it now ？

**Comment by inFreedom92** [comment]
@chen1234520 
It might be "efficientdet-d0" not efficiency

**Comment by chen1234520** [comment]
> @chen1234520
> It might be "efficientdet-d0" not efficiency

 You're right. Thank you very much
